name: travel-platform-ci-cd

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  id-token: write   # This is required for requesting the JWT
  contents: read    # This is required for actions/checkout

env:
  AWS_REGION: ap-south-2

  ECR_REGISTRY: 949474133081.dkr.ecr.ap-south-2.amazonaws.com

  APP_REPOSITORY: travel-app-repo
  WORKER_REPOSITORY: travel-worker-repo
  
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::949474133081:role/travel_platform_github_role
          aws-region: ${{ env.AWS_REGION }}

      - name: Login to ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image
        run: |
          docker build -t $ECR_REGISTRY/$APP_REPOSITORY:latest ./app
          docker build -f ./app/Dockerfile.worker -t $ECR_REGISTRY/$WORKER_REPOSITORY:latest ./app

      - name: Tag images
        run: |
          docker tag $ECR_REGISTRY/$APP_REPOSITORY:latest $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG
          docker tag $ECR_REGISTRY/$WORKER_REPOSITORY:latest $ECR_REGISTRY/$WORKER_REPOSITORY:$IMAGE_TAG

      - name: Push to ECR
        run: |
          docker push $ECR_REGISTRY/$APP_REPOSITORY:latest
          docker push $ECR_REGISTRY/$APP_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$WORKER_REPOSITORY:latest
          docker push $ECR_REGISTRY/$WORKER_REPOSITORY:$IMAGE_TAG

      - name: Trigger SSM Deployment
        run: |
          aws ssm send-command \
          --document-name "AWS-RunShellScript" \
          --targets "Key=tag:Role,Values=app" \
          --parameters "commands=[\"/home/ec2-user/update_app.sh $IMAGE_TAG\",\"/home/ec2-user/update_worker.sh $IMAGE_TAG\"]" \
          --region ${{ env.AWS_REGION }}